repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: forbid-new-submodules
      - id: detect-private-key
      - id: detect-aws-credentials
        args:
          - --allow-missing-credentials
      - id: check-merge-conflict
      - id: no-commit-to-branch
        args:
          - --branch=main
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md
      - id: end-of-file-fixer
      - id: check-xml
      - id: check-yaml
        args:
          - --unsafe
      - id: check-toml
      - id: check-json
        exclude: \.vscode/settings\.json
      - id: check-symlinks
      - id: debug-statements
      - id: check-added-large-files
        args:
          - --maxkb=500
        exclude: (?i)^data/large/.*
      - id: check-illegal-windows-names
      - id: check-case-conflict
      - id: name-tests-test

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.8.3
    hooks:
      - id: commitizen
        stages: [commit-msg]
        always_run: false

  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint
        stages: [commit-msg]
        always_run: false

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.13
    hooks:
      - id: ruff
        name: ruff check
        args:
          - --config=ruff.toml

  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
        name: lint dockerfiles
        files: (?i).*dockerfile

  - repo: local
    hooks:
      - id: check-unix-filenames
        name: check unix/linux filename validity
        entry: bash cli/check_unix_filenames.sh
        language: system
        types: [file]

      - id: export-dependencies
        name: export dependencies
        entry: bash cli/export_deps.sh
        language: system
        types: [file]
        pass_filenames: false

      - id: unit-tests
        name: checking unit tests
        entry: poetry run python -m unittest discover -s tests/unit -p "*.py"
        language: system
        types: [file]
        pass_filenames: false

      - id: integration-tests
        name: checking integration tests
        entry: poetry run python -m unittest discover -s tests/integration -p "*.py"
        language: system
        types: [file]
        pass_filenames: false
