repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: no-commit-to-branch
      - id: check-ast
      - id: check-docstring-first
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-json
      - id: check-xml
      - id: check-yaml
      - id: check-toml
      - id: pretty-format-json
      - id: debug-statements
      - id: detect-private-key
      - id: check-added-large-files
      - id: check-illegal-windows-names
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: name-tests-test
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.4.1
    hooks:
      - id: commitizen
        # args: [.git/COMMIT_EDITMSG]
        # pass_filenames: false
        stages: [commit-msg]
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint
        stages: [commit-msg]
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        args: [--severity=warning]
        types: [shell]
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.8
    hooks:
      - id: bandit
        args: [-r, .]
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: [--profile=flake8]
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        args: [--convention=pep257]
  - repo: https://github.com/jendrikseipp/vulture
    rev: v2.14
    hooks:
      - id: vulture
        args: [--min-confidence=90, --ignore-decorators]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.931
    hooks:
      - id: mypy
        args: [--disallow-untyped-defs, --disallow-incomplete-defs, --disallow-untyped-calls]
  - repo: https://github.com/pycqa/flake8
    rev: 7.2.0
    hooks:
      - id: flake8
        args: [--max-line-length=100, --ignore=E203, --max-complexity=10]
  - repo: local
    hooks:
      - id: check-unix-filenames
        name: check unix/linux filename validity
        entry: bash cli/check_unix_filenames.sh
        language: system
        types: [file]
      - id: export-dependencies
        name: export dependencies
        entry: bash cli/export_deps.sh
        language: system
        types: [file]
        pass_filenames: false
      - id: unit-tests
        name: checking unit tests
        entry: poetry run python -m unittest discover -s tests/unit -p "*.py"
        language: system
        types: [file]
        pass_filenames: false
      - id: integration-tests
        name: checking integration tests
        entry: poetry run python -m unittest discover -s tests/integration -p "*.py"
        language: system
        types: [file]
        pass_filenames: false
