repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: no-commit-to-branch
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-xml
      - id: check-yaml
      - id: check-toml
      - id: debug-statements
      - id: detect-private-key
      - id: check-added-large-files
      - id: check-illegal-windows-names
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: name-tests-test

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.8.3
    hooks:
      - id: commitizen
        stages: [commit-msg]
        always_run: false

  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint
        stages: [commit-msg]
        always_run: false

  - repo: https://github.com/pycqa/flake8
    rev: 7.2.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-annotations==3.1.1
          - flake8-bandit==4.1.1
          - darglint==1.8.1
          - flake8-bugbear==24.12.12
          - flake8-eradicate==1.5.0
        args:
          # vulture
          - --min-confidence=90
          # darglint
          - --darglint-strictness=full
          - --darglint-style=numpy
          # general flake8
          - --max-line-length=99
          - --max-complexity=10
          - --exclude=.git,__pycache__,build,dist,.eggs,.tox,.venv,.env,*.egg-info,*.egg,*.pyc,*.pyo,*.pyd,*.db,*.sqlite3,*.log

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args:
          - --profile=black
          - --force-sort-within-sections
          - --force-alphabetical-sort-within-sections
          - --multi-line GRID
          - --line-length=99

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.0
    hooks:
      - id: mypy
        args:
          - --disallow-untyped-defs
          - --disallow-incomplete-defs
          - --disallow-untyped-calls

  - repo: https://github.com/jendrikseipp/vulture
    rev: v2.7
    hooks:
      - id: vulture
        args:
          - --min-confidence=90

  - repo: local
    hooks:
      - id: check-unix-filenames
        name: check unix/linux filename validity
        entry: bash cli/check_unix_filenames.sh
        language: system
        types: [file]
      - id: export-dependencies
        name: export dependencies
        entry: bash cli/export_deps.sh
        language: system
        types: [file]
        pass_filenames: false
      - id: unit-tests
        name: checking unit tests
        entry: poetry run python -m unittest discover -s tests/unit -p "*.py"
        language: system
        types: [file]
        pass_filenames: false
      - id: integration-tests
        name: checking integration tests
        entry: poetry run python -m unittest discover -s tests/integration -p "*.py"
        language: system
        types: [file]
        pass_filenames: false
