# METADATA: https://airflow.apache.org/docs/apache-airflow/1.10.9/tutorial.html
default_args_airflow:
  owner: "{{owner}}"
  # run task regardless of previous tasks success/failure
  depends_on_past: False
  # email addresses for notification
  email: "{{list_email_addresses}}"
  # send email if task fails
  email_on_failure: True
  # send email if task is retried
  email_on_retry: False
  # delay between retries
  retry_delay: 7200
  # number of retries
  retries: 3
  # use exponential backoff between retries
  retry_exponential_backoff: True
  # backoff factor for exporential backoff
  backoff_factor: 1
  # maximum retry delay
  max_retry_delay: 86400
  start_date: "{{start_date}}"
  end_date: "{{end_date}}"
  # check cron scheduler at: https://crontab.guru/
  schedule_interval: '@daily'
  timezone: UTC
  catchup: False
  on_failure_callback: null
  on_success_callback: null
  on_retry_callback: null
  # default view of dag: graph or tree
  default_view: graph
  # timeout for the whole dag to run
  dagrun_timeout: 7200
  # service level agreement for the dag to run (SLA)
  sla: 7200
  # maximum active runs, of the same dag, at the same time
  max_active_runs: 1
  # callback to trigger when SLA is missed
  sla_miss_callback: null
  # whether to notify when SLA is missed
  sla_notified: False
