name: PR Validation to Main

on:
  pull_request:
    branches:
      - main

jobs:
  validate-tests:
    name: Validate Pre-Commit Hooks Before Merge to Main
    uses: ./.github/workflows/precommit_hooks.yaml
    secrets: inherit
